<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\RawMaterial;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class RawMaterialCompleteSeeder extends Seeder
{
    public function run(): void
    {
        $cafizio  = Brand::where('slug', 'cafizio')->first();
        $infuzio  = Brand::where('slug', 'infuzio')->first();
        $epico    = Brand::where('slug', 'epico')->first();
        $fruitaya = Brand::where('slug', 'fruitaya')->first();

        $packaging = Supplier::where('name', 'Packaging Pro Algérie')->first();
        $epices    = Supplier::where('name', 'Épices du Sud')->first();

        $materials = [

            // ── CAFIZIO Arômes ────────────────────────────────────
            [
                'name'              => 'Arôme cannelle poudre halal',
                'sku'               => 'MP-ARO-CANNELLE',
                'brand_id'          => $cafizio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 2,
                'min_stock_alert'   => 0.2,
                'cost_per_unit'     => 8500,
                'notes'             => 'Certifié halal. Cannelle Ceylon préférée.',
            ],
            [
                'name'              => 'Vanille en poudre',
                'sku'               => 'MP-ARO-VANILLE',
                'brand_id'          => $cafizio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 2,
                'min_stock_alert'   => 0.2,
                'cost_per_unit'     => 45000,
                'notes'             => 'Jamais d\'extrait liquide. Poudre uniquement.',
            ],
            [
                'name'              => 'Cacao en poudre non sucré',
                'sku'               => 'MP-ARO-CACAO',
                'brand_id'          => $cafizio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 5,
                'min_stock_alert'   => 0.5,
                'cost_per_unit'     => 3200,
                'notes'             => 'Non sucré, non alcalinisé. 100% pur.',
            ],
            [
                'name'              => 'Arôme caramel beurre salé poudre halal',
                'sku'               => 'MP-ARO-CARAMEL',
                'brand_id'          => $cafizio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 2,
                'min_stock_alert'   => 0.2,
                'cost_per_unit'     => 7500,
                'notes'             => 'Certifié halal. Jamais d\'arôme liquide.',
            ],
            [
                'name'              => 'Arôme noisette grillée poudre',
                'sku'               => 'MP-ARO-NOISETTE',
                'brand_id'          => $cafizio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 2,
                'min_stock_alert'   => 0.2,
                'cost_per_unit'     => 9000,
                'notes'             => 'Noisette naturelle uniquement — éviter synthétique.',
            ],
            [
                'name'              => 'Cardamome verte moulue',
                'sku'               => 'MP-ARO-CARDAMOME',
                'brand_id'          => $cafizio->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 1,
                'min_stock_alert'   => 0.1,
                'cost_per_unit'     => 12000,
                'notes'             => 'Moudre soi-même avant utilisation. Perd son arôme vite.',
            ],
            [
                'name'              => 'Arôme menthe poivrée poudre',
                'sku'               => 'MP-ARO-MENTHE',
                'brand_id'          => $cafizio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 1,
                'min_stock_alert'   => 0.1,
                'cost_per_unit'     => 7000,
                'notes'             => 'Peppermint uniquement. Max 4% — très puissant.',
            ],
            [
                'name'              => 'Café Arabica décaféiné Swiss Water',
                'sku'               => 'MP-CAFE-DECAF',
                'brand_id'          => $cafizio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 100,
                'min_stock_alert'   => 20,
                'cost_per_unit'     => 1200,
                'notes'             => 'Swiss Water Process. Caféine < 0.1%. Exiger certificat.',
            ],

            // ── INFUZIO Plantes ───────────────────────────────────
            [
                'name'              => 'Thé vert en feuilles',
                'sku'               => 'MP-TIS-THE-VERT',
                'brand_id'          => $infuzio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 20,
                'min_stock_alert'   => 3,
                'cost_per_unit'     => 1800,
                'notes'             => 'Feuilles brisées 2-3mm. Humidité < 8%.',
            ],
            [
                'name'              => 'Menthe poivrée séchée',
                'sku'               => 'MP-TIS-MENTHE',
                'brand_id'          => $infuzio->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 10,
                'min_stock_alert'   => 2,
                'cost_per_unit'     => 950,
                'notes'             => 'Sécher à 40°C max. Préparer en petits lots.',
            ],
            [
                'name'              => 'Rooibos en aiguilles',
                'sku'               => 'MP-TIS-ROOIBOS',
                'brand_id'          => $infuzio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 15,
                'min_stock_alert'   => 3,
                'cost_per_unit'     => 2200,
                'notes'             => 'Aiguilles brisées 2-4mm. Sans caféine.',
            ],
            [
                'name'              => 'Matcha en poudre',
                'sku'               => 'MP-TIS-MATCHA',
                'brand_id'          => $infuzio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 5,
                'min_stock_alert'   => 1,
                'cost_per_unit'     => 8500,
                'notes'             => 'Humidité < 5%. Très hygroscopique. Stocker avec dessiccant.',
            ],
            [
                'name'              => 'Fenouil séché',
                'sku'               => 'MP-TIS-FENOUIL',
                'brand_id'          => $infuzio->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 8,
                'min_stock_alert'   => 1,
                'cost_per_unit'     => 750,
                'notes'             => 'Pour mélange digestif. Sécher à 45°C max.',
            ],
            [
                'name'              => 'Anis vert séché',
                'sku'               => 'MP-TIS-ANIS',
                'brand_id'          => $infuzio->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 8,
                'min_stock_alert'   => 1,
                'cost_per_unit'     => 800,
                'notes'             => 'Pour mélange digestif.',
            ],
            [
                'name'              => 'Gingembre séché en poudre',
                'sku'               => 'MP-TIS-GINGEMBRE',
                'brand_id'          => $infuzio->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 10,
                'min_stock_alert'   => 2,
                'cost_per_unit'     => 1200,
                'notes'             => 'Sécher 60°C 6h si frais. Broyer 80-100 mesh.',
            ],
            [
                'name'              => 'Citron séché en poudre',
                'sku'               => 'MP-TIS-CITRON',
                'brand_id'          => $infuzio->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 5,
                'min_stock_alert'   => 1,
                'cost_per_unit'     => 1500,
                'notes'             => 'Zeste séché broye 80 mesh. Pour INFUZIO GINGEMBRE.',
            ],

            // ── EPICO Épices manquantes ───────────────────────────
            [
                'name'              => 'Cannelle moulue',
                'sku'               => 'MP-EPI-CANNELLE',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 50,
                'min_stock_alert'   => 5,
                'cost_per_unit'     => 1800,
                'notes'             => 'Pour Ras el Hanout et Tandoori.',
            ],
            [
                'name'              => 'Poivre noir moulu',
                'sku'               => 'MP-EPI-POIVRE',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 40,
                'min_stock_alert'   => 5,
                'cost_per_unit'     => 1400,
                'notes'             => 'Pour mélanges.',
            ],
            [
                'name'              => 'Cardamome moulue',
                'sku'               => 'MP-EPI-CARDAMOME',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 20,
                'min_stock_alert'   => 3,
                'cost_per_unit'     => 9500,
                'notes'             => 'Pour Ras el Hanout et Tandoori.',
            ],
            [
                'name'              => 'Gingembre moulu',
                'sku'               => 'MP-EPI-GINGEMBRE',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 30,
                'min_stock_alert'   => 5,
                'cost_per_unit'     => 1200,
                'notes'             => 'Pour mélanges.',
            ],
            [
                'name'              => 'Curcuma moulu',
                'sku'               => 'MP-EPI-CURCUMA',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 50,
                'min_stock_alert'   => 5,
                'cost_per_unit'     => 900,
                'notes'             => 'Tache définitivement. Ustensiles dédiés.',
            ],
            [
                'name'              => 'Ail en poudre',
                'sku'               => 'MP-EPI-AIL',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 30,
                'min_stock_alert'   => 5,
                'cost_per_unit'     => 650,
                'notes'             => 'Acheté déjà en poudre. Humidité < 5%.',
            ],
            [
                'name'              => 'Oignon en poudre',
                'sku'               => 'MP-EPI-OIGNON',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 30,
                'min_stock_alert'   => 5,
                'cost_per_unit'     => 550,
                'notes'             => 'Acheté déjà en poudre. Pour BBQ.',
            ],
            [
                'name'              => 'Noix de muscade moulue',
                'sku'               => 'MP-EPI-MUSCADE',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 10,
                'min_stock_alert'   => 1,
                'cost_per_unit'     => 4500,
                'notes'             => 'Pour Ras el Hanout.',
            ],
            [
                'name'              => 'Clous de girofle moulus',
                'sku'               => 'MP-EPI-GIROFLE',
                'brand_id'          => $epico->id,
                'supplier_id'       => $epices->id,
                'unit'              => 'kg',
                'quantity_in_stock' => 5,
                'min_stock_alert'   => 0.5,
                'cost_per_unit'     => 6500,
                'notes'             => 'Pour Ras el Hanout.',
            ],

            // ── FRUITAYA Fruits manquants ────────────────────────
            [
                'name'              => 'Bananes fraîches',
                'sku'               => 'MP-FRT-BANANE',
                'brand_id'          => $fruitaya->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 200,
                'min_stock_alert'   => 20,
                'cost_per_unit'     => 80,
                'notes'             => 'Bien mûres avec quelques taches. Perte 70%.',
            ],
            [
                'name'              => 'Fraises fraîches',
                'sku'               => 'MP-FRT-FRAISE',
                'brand_id'          => $fruitaya->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 100,
                'min_stock_alert'   => 10,
                'cost_per_unit'     => 350,
                'notes'             => 'Fermes, bien rouges. Perte 85%.',
            ],
            [
                'name'              => 'Mangues fraîches',
                'sku'               => 'MP-FRT-MANGUE',
                'brand_id'          => $fruitaya->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 150,
                'min_stock_alert'   => 15,
                'cost_per_unit'     => 180,
                'notes'             => 'Peau jaune-orange, chair ferme. Perte 75%.',
            ],
            [
                'name'              => 'Pommes fraîches',
                'sku'               => 'MP-FRT-POMME',
                'brand_id'          => $fruitaya->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 200,
                'min_stock_alert'   => 20,
                'cost_per_unit'     => 120,
                'notes'             => 'Golden ou Granny Smith. Bain citron OBLIGATOIRE. Perte 75%.',
            ],
            [
                'name'              => 'Cerises fraîches',
                'sku'               => 'MP-FRT-CERISE',
                'brand_id'          => $fruitaya->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 50,
                'min_stock_alert'   => 5,
                'cost_per_unit'     => 450,
                'notes'             => 'Bien mûres et fermes. Perte 75%. Produit premium.',
            ],
            [
                'name'              => 'Kiwis frais',
                'sku'               => 'MP-FRT-KIWI',
                'brand_id'          => $fruitaya->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 100,
                'min_stock_alert'   => 10,
                'cost_per_unit'     => 220,
                'notes'             => 'Mûrs mais encore fermes. Perte 80%.',
            ],
            [
                'name'              => 'Ananas frais',
                'sku'               => 'MP-FRT-ANANAS',
                'brand_id'          => $fruitaya->id,
                'supplier_id'       => null,
                'unit'              => 'kg',
                'quantity_in_stock' => 150,
                'min_stock_alert'   => 15,
                'cost_per_unit'     => 160,
                'notes'             => 'Peau jaune-orange, odeur sucrée. Perte 80%.',
            ],

            // ── Packaging supplémentaire ─────────────────────────
            [
                'name'              => 'Doypacks 100g',
                'sku'               => 'MP-DOYPACK-100',
                'brand_id'          => null,
                'supplier_id'       => $packaging->id,
                'unit'              => 'piece',
                'quantity_in_stock' => 5000,
                'min_stock_alert'   => 500,
                'cost_per_unit'     => 12,
                'notes'             => 'Pour EPICO format 100g.',
            ],
        ];

        foreach ($materials as $material) {
            RawMaterial::create($material);
        }
    }
}